---
title: "day_4_ Hexagons"
output: html_document
date: "2024-11-05"
---

```{r setup, include=FALSE}
library(hkdatasets)
library(sf)
library(dplyr)
library(mapview)
library(tmap)
library(ggplot2)
library(viridis)  # For a color palette similar to Reds

setwd("/Users/jiatong/Desktop/30daysMap/day4_hext")
```

## R Markdown

https://urbandatapalette.com/post/2021-08-tessellation-sf/ 
```{r}
HK_district <- st_read("https://services3.arcgis.com/6j1KwZfY2fZrfNMR/arcgis/rest/services/Hong_Kong_18_Districts/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson")

CW_hk <- HK_district %>% filter(CNAME == "中西區") %>% st_transform(2326)

```

```{r}
hk_accidents = hkdatasets::download_data("hk_accidents")

test_data = subset(hk_accidents, District_Council_District == "CW" & Year == 2019)

# turn it to sf object
test_points = test_data %>%
  # lng/lat value are missing in some records
  filter(!is.na(Grid_E) & !is.na(Grid_N)) %>%
  st_as_sf(coords = c("Grid_E", "Grid_N"), crs = 2326, remove = FALSE)

```

```{r}
area_fishnet_grid = st_make_grid(test_points, c(150, 150), what = "polygons", square = TRUE)

# To sf and add grid ID
fishnet_grid_sf = st_sf(area_fishnet_grid) %>%
  # add grid ID
  mutate(grid_id = 1:length(lengths(area_fishnet_grid)))

# count number of points in each grid
# https://gis.stackexchange.com/questions/323698/counting-points-in-polygons-with-sf-package-of-r
fishnet_grid_sf$n_colli = lengths(st_intersects(fishnet_grid_sf, test_points))

# remove grid without value of 0 (i.e. no points in side that grid)
fishnet_count = filter(fishnet_grid_sf, n_colli > 0)
```

```{r}
area_honeycomb_grid = st_make_grid(test_points, c(150, 150), what = "polygons", square = FALSE)

# To sf and add grid ID
honeycomb_grid_sf = st_sf(area_honeycomb_grid) %>%
  # add grid ID
  mutate(grid_id = 1:length(lengths(area_honeycomb_grid)))

# count number of points in each grid
# https://gis.stackexchange.com/questions/323698/counting-points-in-polygons-with-sf-package-of-r
honeycomb_grid_sf$n_colli = lengths(st_intersects(honeycomb_grid_sf, test_points))

# remove grid without value of 0 (i.e. no points in side that grid)
honeycomb_count = filter(honeycomb_grid_sf, n_colli > 0)
```

```{r}
tmap_mode("view")

map_honeycomb = tm_shape(honeycomb_count) +
  tm_fill(
    col = "n_colli",
    palette = "Reds",
    style = "cont",
    title = "Number of collisions",
    id = "grid_id",
    showNA = FALSE,
    alpha = 0.6,
    popup.vars = c(
      "Number of collisions: " = "n_colli"
    ),
    popup.format = list(
      n_colli = list(format = "f", digits = 0)
    )
  ) +
  tm_borders(col = "grey40", lwd = 0.7) + 
  tm_layout(
    title = "Collisions in Central West District in Hong Kong, 2019",
    title.size = 1.5,  # Adjust size as needed
    title.position = c("center", "top")  # Position title at top center
  ) +
  tm_credits(
    text = "Created by Jiatong Su | @weitzman_musa | #30daysMapChallenge | Day4 - Hexagon",
    position = c("right", "bottom"),  # Adjust position as desired
    size = 0.8                        # Adjust size for readability
  )

map_honeycomb
```

```{r}
tmap_save(map_honeycomb, "day_4.html")

```



```{r}
hk_cw_collison_1 <- ggplot() +
  xlim(827500, 837550) +
  ylim(812047, 819047) +
  
  geom_sf(data = CW_hk, fill = "lightyellow", color = NA) +  # Central West Hong Kong layer
  geom_sf(data = HK_district, fill = "lightyellow", color = NA, alpha = 0.5) +  # Hong Kong districts layer
  geom_sf(data = honeycomb_count, aes(fill = n_colli), color = "grey40", size = 0.2) +  # Honeycomb layer with fill based on n_colli
  
  scale_fill_viridis(
    option = "C",  # Reds palette alternative
    name = "Number of collisions",
    direction = -1,
  guide = guide_colorbar(direction = "horizontal") # Use guide_colorbar for a horizontal continuous legend

  ) +
  
  theme_minimal() +
  theme_void() +
  theme(
    panel.background = element_rect(fill = "lightblue", color = NA),
    plot.caption = element_text(hjust = 0),
    legend.position = c(0.70, 0.05),
    legend.title = element_text(color = "darkblue"),  # Set legend title text color

    legend.text = element_text(color = "darkblue")  # Set legend text color
   ) +

  # Add title
  geom_text(
    aes(x = 827500, y = 819047), 
    label = "Collisions in Central West District, 2019",
    size = 6, hjust = 0, color = "darkblue"
  ) +

  # Add subtitle
  geom_text(
    aes(x = 827500, y = 818647), 
    label = "Data Source: Hong Kong Districts Info | Created by Jiatong Su",
    size = 4, hjust = 0, color = "darkblue"
  ) +
  
  # Add caption
  geom_text(
    aes(x = 827500, y = 812547),
    label = "30 day map challenge | Day4 - Hexagon\nAuthor: Jiatong Su\nData Source: Hong Kong Districts Info\n@weitzman_musa",
    size = 2.5, hjust = 0, color = "darkblue"
  )

hk_cw_collison_1
```

```{r}
ggsave("day_4.png", plot = hk_cw_collison_1)

```
